version: 0.2

phases:
    commands:
      # Install dependencies needed for running tests
      - npm install
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      # - npm test
      # Upgrade AWS CLI to the latest version
      - mkdir mkdir test_report
      - npm run test 2>&1 | tee ./test_report/test_result.txt
      - npm run test:e2e 2>&1 | tee -a ./test_report/test_result.txt
reports:
  StateMachineUnitTestReports:
    files:
      - "**/*"
    base-directory: "test_report"